---
- name: Verificação Pós-Provisionamento (Arista)
  hosts: "{{ target_hostname }}"
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: Abortar Playbook INTEIRO se o Survey não for Arista
      ansible.builtin.meta: end_play
      when: target_group != "arista_switches"

    - name: Executar comandos de validação (Arista)
      arista.eos.eos_command:
        commands:
          - show version
          - show ip interface brief
          - show ip ospf neighbor
          - show ip bgp summary
          - show running-config
      register: arista_output

    - name: Exibir Relatório de Validação (Arista)
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - " RELATÓRIO DE VALIDAÇÃO - ARISTA EOS "
          - "=========================================="
          - ">>> SHOW IP INTERFACE BRIEF <<<"
          - "{{ arista_output.stdout[1] }}"
          - ">>> SHOW IP OSPF NEIGHBOR <<<"
          - "{{ arista_output.stdout[2] }}"
          - ">>> SHOW IP BGP SUMMARY <<<"
          - "{{ arista_output.stdout[3] }}"
