---
- name: Provisionamento Cisco
  hosts: all
  tasks:
    - name: Abortar se não for grupo Cisco
      ansible.builtin.meta: end_host
      when: target_group != "cisco_routers"

    - name: Configurar Hostname
      cisco.ios.ios_hostname:
        name: "{{ target_hostname }}"

    - name: Configurar IP na Interface Física
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ physical_interface }}"
            ipv4:
              - address: "{{ ipv4_address }}"
        state: merged
