---
- name: Provisionamento Arista
  hosts: all
  tasks:
    - name: Abortar se não for grupo Arista
      ansible.builtin.meta: end_host
      when: target_group != "arista_switches"

    - name: Configurar Hostname
      arista.eos.eos_hostname:
        hostname: "{{ target_hostname }}"

    - name: Criar Interface VLAN
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ arista_vlan_info.split(',')[0] }}"
            name: "{{ arista_vlan_info.split(',')[1] }}"
        state: merged

    - name: Configurar Porta Física como Trunk ou Access para a VLAN
      arista.eos.eos_l2_interfaces:
        config:
          - name: "{{ physical_interface }}"
            access:
              vlan: "{{ arista_vlan_info.split(',')[0] }}"
        state: merged

    - name: Atribuir IP à Interface VLAN (SVI)
      arista.eos.eos_l3_interfaces:
        config:
          - name: "Vlan{{ arista_vlan_info.split(',')[0] }}"
            ipv4:
              - address: "{{ ipv4_address }}"
        state: merged
