---
- name: Provisionamento Cisco com Usuário Ansible
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Abortar se não for grupo Cisco
      ansible.builtin.meta: end_host
      when: target_group != "cisco_routers"

    - name: Criar Usuário Ansible com Privilégio 15
      cisco.ios.ios_user:
        name: ansible
        privilege: 15
        configured_password: redhat
        state: present
      ignore_errors: yes  # Se já existir ou der erro de auth, ele pula para a próxima

    - name: Configurar Hostname
      cisco.ios.ios_hostname:
        config:
          name: "{{ target_hostname }}"
        state: merged

    - name: Configurar IP na Interface Física
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ physical_interface }}"
            ipv4:
              - address: "{{ ipv4_address }}"
        state: merged
