---
- name: Provisionamento Cisco com Usuário Ansible
  hosts: "{{ target_hostname }}"
  gather_facts: no
  
  tasks:
    - name: Abortar Playbook INTEIRO se o Survey não for Cisco
      ansible.builtin.meta: end_play
      when: target_group != "cisco_routers"
      
    - name: Criar Usuário Ansible com Privilégio 15
      cisco.ios.ios_user:
        name: ansible
        privilege: 15
        configured_password: Ansible@123
        state: present
      ignore_errors: yes

    - name: Configurar Hostname (via comando CLI puro)
      cisco.ios.ios_config:
        lines:
          - "hostname {{ target_hostname }}"

    - name: Configurar IP na Interface Física
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ physical_interface }}"
            ipv4:
              - address: "{{ ipv4_address }}"
        state: merged

    - name: Garantir Acesso VTY
      cisco.ios.ios_config:
        parents: line vty 0 4
        lines:
          - login local
          - transport input ssh
