---
- name: Provisionamento Arista com Usuário Ansible
  hosts: all
  gather_facts: no
  tasks:
    - name: Abortar Playbook INTEIRO se o Survey não for Arista
      ansible.builtin.meta: end_play
      when: target_group != "arista_switches"

    - name: Criar Usuário Ansible Administrativo
      arista.eos.eos_user:
        name: ansible
        privilege: 15
        role: network-admin
        configured_password: redhat
        state: present
      ignore_errors: yes

    - name: Configurar Hostname (Arista)
      arista.eos.eos_config:
        lines:
          - "hostname {{ target_hostname }}"

    - name: Criar VLAN
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ arista_vlan_info.split(',')[0] | trim }}"
            name: "{{ arista_vlan_info.split(',')[1] | trim }}"
        state: merged

    - name: Configurar Porta Física (Acesso VLAN)
      arista.eos.eos_l2_interfaces:
        config:
          - name: "{{ physical_interface }}"
            access:
              vlan: "{{ arista_vlan_info.split(',')[0] | trim }}"
        state: merged

    - name: Atribuir IP à SVI (Interface VLAN)
      arista.eos.eos_l3_interfaces:
        config:
          - name: "Vlan{{ arista_vlan_info.split(',')[0] | trim }}"
            ipv4:
              - address: "{{ ipv4_address }}"
        state: merged
