---
collections:
  # Coleção para gerir o AWX/Controller via API
  - name: awx.awx
    version: '>=23.0.0'

  # Coleções de rede para o seu lab
  - name: cisco.ios
  - name: arista.eos
  
  # Recomendado: Usar a collection moderna da Juniper
  - name: juniper.device
  - name: ansible.netcommon
